# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3fc0d7d5d3a4ef69967e3c713c4a4b039cf72349b4101fb959976d5510b37cae9f1dd5502b025de9be720f59a8594587cadddf8f7d608df755da1197b92ed2e5

test:
  secret_key_base: 03d869b718f9322d088cbc892ad8b3cc823379b5a3ef5917abff7281dd365ff02c61768cb864e8375974acdd0455f89b77798a71f08da9d5e5d010bccc2b1e60

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
